Identity = "Chronos1"
NodeName = "Chronos1-Node"
RpcAddress = "tcp://127.0.0.1:26601"
P2PAddress = "tcp://127.0.0.1:26611"
AppAddress = "tcp://127.0.0.1:26621"
SDKAddress = "tcp://127.0.0.1:26631"
OLVMAddress = "tcp://127.0.0.1:26641"
OLVMProtocol = "tcp"
BTCAddress = "127.0.0.1:NONE"
ETHAddress = "NONE"
